(function(){
 const el=document.documentElement.lang==='el';
 const labels=el?{home:'Αρχική',series:'Η σειρά',artist:'Ο πιανίστας',concerts:'Συναυλίες',settings:'Ρυθμίσεις',title:'Ρυθμίσεις εμφάνισης',text:'Επιλογή γλώσσας για αυτή την παρουσίαση.',language:'Γλώσσα',close:'Κλείσιμο',menu:'Άνοιγμα μενού',menuClose:'Κλείσιμο μενού'}:{home:'Home',series:'The series',artist:'The pianist',concerts:'Concerts',settings:'Settings',title:'Display settings',text:'Choose the language for this preview.',language:'Language',close:'Close',menu:'Open menu',menuClose:'Close menu'};
 const base=el?'/el.html':'/';const menuBtn=document.querySelector('.menu-button');let panel=null,overlay=null,dialog=null;
 function closeMenu(){panel?.remove();overlay?.remove();panel=overlay=null;menuBtn.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');menuBtn.setAttribute('aria-label',labels.menu)}
 function closeDialog(){dialog?.remove();dialog=null;document.body.style.overflow='';}
 menuBtn.addEventListener('click',()=>{if(panel){closeMenu();return}overlay=document.createElement('button');overlay.className='menu-scrim';overlay.setAttribute('aria-label',labels.close);overlay.addEventListener('click',closeMenu);panel=document.createElement('div');panel.className='menu-panel';panel.id='site-menu';panel.innerHTML=`<a href="${base}">${labels.home}</a><a href="#series">${labels.series}</a><a href="#artist">${labels.artist}</a><a href="#concerts">${labels.concerts}</a><button type="button">${labels.settings}</button>`;document.querySelector('.site-header').append(overlay,panel);menuBtn.classList.add('open');menuBtn.setAttribute('aria-expanded','true');menuBtn.setAttribute('aria-label',labels.menuClose);panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));panel.querySelector('button').addEventListener('click',()=>{closeMenu();openSettings()})});
 function openSettings(){dialog=document.createElement('div');dialog.className='modal-backdrop';dialog.innerHTML=`<div class="settings-dialog" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div class="dialog-top"><h2 id="settings-title">${labels.title}</h2><button type="button" aria-label="${labels.close}">×</button></div><p>${labels.text}</p><div class="setting-row"><span>${labels.language}</span><div class="language large"><a href="/el.html" ${el?'aria-current="page"':''}>ΕΛ</a><span>/</span><a href="/" ${!el?'aria-current="page"':''}>EN</a></div></div><button class="dialog-close" type="button">${labels.close}</button></div>`;document.body.append(dialog);document.body.style.overflow='hidden';dialog.querySelector('.dialog-top button').focus();dialog.querySelectorAll('button').forEach(b=>b.addEventListener('click',closeDialog));dialog.addEventListener('mousedown',e=>{if(e.target===dialog)closeDialog()})}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();closeDialog()}});
 document.querySelectorAll('.language button').forEach(b=>b.addEventListener('click',()=>{const dest=b.textContent.trim()==='ΕΛ'?'/el.html':'/';if(location.pathname!==dest)location.href=dest}));
 document.querySelector('.brand').setAttribute('href',base);
 const style=document.createElement('style');style.textContent='.language.large a{font-size:14px;color:#817a8b}.language.large a[aria-current="page"]{color:#211d29;font-weight:600}';document.head.append(style);
})();
